### ISSUE TITLE
Suggestion: using FRAM

### ISSUE THREAD

**Issue by 8lall0** [shilga/rp2040-gameboy-cartridge-firmware#3]
Hello,
in your opinion, would be possible to use FRAM for storing saves?

My idea would be:
Games can save data in FRAM, like a normal FRAM mod ([link](https://www.reddit.com/r/Gameboy/comments/fe3tec/non_volatile_fram_replacement_for_game_boy_with/)), even with a FM28v020 which is cheaper and can work at 3.3v with some level shifting.

If the Pico detects a save, can simply read the FRAM and store it somewhere (maybe using the second core), while saving for the games would be absolutely transparent.

**Comment by shilga** [comment]
Hi,
as much as I like the idea of FRAMs it would not really make sense in this project as it is right now. The target of this project was to create a cheap cartridge by doing nearly everything in software. That is also why the internal RAM of the RP2040 is used. Using the FM28v020 would just double the price of the cartridge. Besides the fact that there are not enough pins on the RP2040 to control everything correctly. Maybe at a later date if Raspberry Foundation decides to make a bigger microcontroller. 

Or maybe I will create a version 2 at some point which has an battery backed battery, which could also be used to let a RAM be powered while the Game Boy is off. When the save could be stored on startup.

If you want the comfort of a FRAM I would suggest getting an Everdrive. The only advantage of creating such a cartridge would be to make it FOSS. But it would probably not be cheaper.

Your suggestion about saving it transparent in the background would be theoretically possible today as the savegame is already in the RP2040. But the problem is that ROM is loaded in real time from the flash and while storing the savegame to it the ROM can't be accessed anymore.

I suggest to try the new feature to trigger storing the save with the help of the savegame hook and a button combination on the Game Boy. Sadly it does not work with all games yet.
